### PR TITLE
Examples: Added Crypto

### PR DESCRIPTION
**Pull request by sadath-12**
# Description

Taking direct reference from ```https://github.com/dapr/quickstarts/tree/master/cryptography/go/sdk```

The reason to add it here is to make sure our linter detects if any buggy changes happening to crypto code

## Issue reference

Please reference the issue this PR will close: #395 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by mikeee** [comment]
I'm all for adding validation flows to the sdk. Just not sure about committing relatively large binaries from the quickstarts to the repo.

**Comment by daixiang0** [comment]
Use a markdown file with little words is enough, we can comment it ( the file type and size we support etc.) in the doc

**Comment by sadath-12** [comment]
so just the ```examples/crypto/README.md``` enough ?

**Comment by sadath-12** [comment]
> I'm all for adding validation flows to the sdk. Just not sure about committing relatively large binaries from the quickstarts to the repo.

which large binaries?

**Comment by sadath-12** [comment]
its just one ```main.go``` which would also help us to validate in our ci easily

**Review by yaron2 — APPROVED** [review]

**Comment by mikeee** [comment]
This needs to be added to the validation workflow to have any effect on CI. 
I'll get a PR raised

**Pull request merged**
