### PR TITLE
Fix CODEOWNERS

### PR DESCRIPTION
**Pull request by AaronCrawfis**

### CODE REVIEW

**Comment by yaron2** [comment]
@AaronCrawfis are we adding docs maintainers to CODEOWNERS for every repo?

**Comment by daixiang0** [comment]
I see it in https://github.com/dapr/community/blob/master/community-membership.md, maybe we can point this link in each repo.

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis are we adding docs maintainers to CODEOWNERS for every repo?

@yaron2 just the SDK repos, and just for the daprdocs folder.

**Comment by artursouza** [comment]
LGTM but I cannot approve in this repo.

**Comment by daixiang0** [comment]
ping @yaron2

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
