### PR TITLE
fix readme.md

### PR DESCRIPTION
**Pull request by yaoliu**
if http.ServeMux already exists Use NewServiceWithMux

### CODE REVIEW

**Comment by yaoliu** [comment]
flx readme.md

**Comment by yaoliu** [comment]
fix eventHandler

**Comment by yaoliu** [comment]
fix readme.md

**Comment by yaoliu** [comment]
flx grpc readme.md

**Comment by yaoliu** [comment]
flx grpc readme.md

**Review by yaron2 — APPROVED** [review]
LGTM

**Pull request merged**
