### PR TITLE
Enhance workFlow to add go mod tidy

### PR DESCRIPTION
**Pull request by kruthika04**
Addresses https://github.com/dapr/go-sdk/issues/450 
Added job to ccheck for if the go mod needs updating when we create pull requests

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
LGTM. 
Thanks for the contribution !! 
Consider adding modtidy-all for checking examples also? @yaron2 @dapr/maintainers-go-sdk thoughts?

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by kruthika04** [comment]
> LGTM. Thanks for the contribution !! Consider adding modtidy-all for checking examples also? @yaron2 @dapr/maintainers-go-sdk thoughts?

sure that would be good 
@yaron2 @dapr/maintainers-go-sdk 
Do I add it here ?

**Review by dasanind — APPROVED** [review]
LGTM

**Review by sicoyle — APPROVED** [review]
LGTM, thank you for your Grace Hopper Conference Open Source Day contribution! 🚀

**Comment by sicoyle** [comment]
> LGTM. Thanks for the contribution !! Consider adding modtidy-all for checking examples also?

Can you please add @kruthika04 ?

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Thank you for your contribution!

**Pull request merged**
