### PR TITLE
Implement distributed scheduler building block

### PR DESCRIPTION
**Pull request by mikeee**
# Description

- Registers a new alpha appcallback server
- Implements an empty onbulktopicevent handler that will panic
- Implements the alpha job api and appcallback registration
- Misc changes to the examples - fixing conflicts with the default scheduler port
- Updates the validation workflow to enable building from custom commits using events

## Issue reference

Please reference the issue this PR will close: #561 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
What's needed for this to go out of draft?

**Comment by mikeee** [comment]
> What's needed for this to go out of draft?

I've rerun this and the jobs aren't being invoked. I'll need to take a look at this tomorrow with fresh eyes

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
@mikeee this looks great from my side. ready to merge?

**Review by mikeee — COMMENTED** [review]
self-review

**Pull request merged**
