### PR TITLE
Change configuration API response to dictionary

### PR DESCRIPTION
**Pull request by hunter007**
When https://github.com/dapr/dapr/pull/4695 merged, I will test the PR, then it should be reviewed by someone.

the PR can be merged after that https://github.com/dapr/dapr/pull/4695 is merged.

Related issues: #291

### CODE REVIEW

**Comment by addjuarez** [comment]
The changes to dapr have been merged https://github.com/dapr/dapr/pull/5083 . You should be unblocked now.

**Comment by shubham1172** [comment]
@daixiang0 @yaron2 @skyao can you please help with unblocking this, CLI RC is blocked.

**Comment by hunter007** [comment]
> @daixiang0 @yaron2 @skyao can you please help with unblocking this, CLI RC is blocked.

I fix it now :)

**Comment by hunter007** [comment]
@daixiang0 @yaron2 @skyao review the pr please.

**Comment by yaron2** [comment]
@hunter007 please see failing tests

**Comment by yaron2** [comment]
There's linter failures. As we need to get these changes merged quickly we're probably going to merge https://github.com/dapr/go-sdk/pull/323/files.

**Comment by hunter007** [comment]
> looks like lint error because of ci cache. Can you solve the error for me?

**Comment by hunter007** [comment]
> There's linter failures. As we need to get these changes merged quickly we're probably going to merge https://github.com/dapr/go-sdk/pull/323/files.

ok

**Comment by yaron2** [comment]
@hunter007 thanks for opening this PR. https://github.com/dapr/go-sdk/pull/323 is now merged, however your PR has the latest version of the Dapr proto files.

We would love to accept a PR that updates `dapr/go-sdk` with the latest proto files!

**Comment by hunter007** [comment]
> @hunter007 thanks for opening this PR. #323 is now merged, however your PR has the latest version of the Dapr proto files.
> 
> We would love to accept a new PR that updates `dapr/go-sdk` with the latest proto files!

I see. this PR is too big

**Pull request closed without merging**
