### PR TITLE
[service/http]switch from Gorilla Mux to Chi

### PR DESCRIPTION
**Pull request by jackycsl**
Description:
Switch from Gorilla Mux to Chi as Gorilla Mux is no longer maintained.
The APIs remained fairly similar.

Link to tracking Issue:
[#344 ]

Testing:
Regression test are passed.

Documentation:
N/A

### CODE REVIEW

**Comment by robcxyz** [comment]
I think this is a smart decision. Was going to submit PR for the same.

**Review by daixiang0 — APPROVED** [review]

**Comment by jackycsl** [comment]
@daixiang0 Thanks for the approval. Is it possible to re-run the CI scan?

**Comment by daixiang0** [comment]
You need update commit to trigger it, I do not find a button to re-run.

**Comment by daixiang0** [comment]
@[shubham1172](https://github.com/shubham1172) I do not see re-run button in the CI, how to enable it?

**Comment by daixiang0** [comment]
@yaron2 please re-run the CI then we can get it.

**Comment by daixiang0** [comment]
No license issue, skip re-run CI.

**Pull request merged**
