### PR TITLE
fix(security): bump security vulnerabilities

### PR DESCRIPTION
**Pull request by sicoyle**
# Description

Related to efforts to improve security vulnerabilities. Other efforts below that are related:
https://github.com/dapr/dapr/pull/7681
https://github.com/dapr/components-contrib/pull/3390

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Review by mikeee — DISMISSED** [review]
lgtm - I have nothing against this in principle 

Since this suppresses important deprecation notices - there **definitely** should be a follow-up issue created to migrate the way we create grpc client connections going forwards.

**Comment by sicoyle** [comment]
> Since this suppresses important deprecation notices - there definitely should be a follow-up issue created to migrate the way we create grpc client connections going forwards.

yes, I opened one on dapr/dapr, but will open a similar one here as well and everywhere else I made these updates 😁

**Comment by mikeee** [comment]
> > Since this suppresses important deprecation notices - there definitely should be a follow-up issue created to migrate the way we create grpc client connections going forwards.
> 
> yes, I opened one on dapr/dapr, but will open a similar one here as well and everywhere else I made these updates 😁 

I appreciate snyk is unable to process this repo for one reason or another but have you noticed snyk not liking v1.64.0 as it has a dependency on x/net 0.22?

**Comment by sicoyle** [comment]
> I appreciate snyk is unable to process this repo for one reason or another but have you noticed snyk not liking v1.64.0 as it has a dependency on x/net 0.22?

No, I have no insights to see why snyk fails tbh. It failed intermittently on my other security vulnerability bump PRs tbh. I can try v1.63.0 if you'd like and see if it likes that better or see if there is a version that will change the x/net dep

**Comment by mikeee** [comment]
> > I appreciate snyk is unable to process this repo for one reason or another but have you noticed snyk not liking v1.64.0 as it has a dependency on x/net 0.22?
> 
> No, I have no insights to see why snyk fails tbh. It failed intermittently on my other security vulnerability bump PRs too. I can try v1.63.0 if you'd like and see if it likes that better or see if there is a version that will change the x/net dep

I've raised it, I'm not going crazy thankfully. There was an issue updating x/net to v0.22< and I've been told a release is on the way.
This looks good to merge and we should have a minor grpc bump at some point in the future 👍

**Review by mikeee — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @sicoyle Thanks Sam!

**Pull request merged**
