### PR TITLE
ci: add lint in prs

### LINKED ISSUE #168: Introduce golangci-lint
**Is your feature request related to a problem? Please describe.**

I do not see any lint for this, enable lint makes project better I think.

**Describe the solution you'd like**

Introduce golangci-lint.

I have done at local, If possible, I will post it.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

Fix #168

Changes as below:
- add golangci-lint config
- upgrade version to latest
- fix lint issues by defaults

### CODE REVIEW

**Comment by daixiang0** [comment]
@berndverst  @yaron2 please review

**Comment by yaron2** [comment]
Please resolve conflicts.

**Comment by daixiang0** [comment]
@yaron2 done.

**Comment by daixiang0** [comment]
To fix https://github.com/golangci/golangci-lint-action/issues/23, adjust order.

**Comment by daixiang0** [comment]
@yaron2 kindly ping.

**Comment by daixiang0** [comment]
ping @artursouza @yaron2

**Review by artursouza — APPROVED** [review]
@yaron2 Please, review as a maintainer.

**Comment by daixiang0** [comment]
ping @yaron2

**Comment by daixiang0** [comment]
ping @yaron2

**Pull request closed without merging**
