### PR TITLE
optimize(invocation): reduce daprd server's logic processing

### PR DESCRIPTION
**Pull request by 1046102779**

### CODE REVIEW

**Comment by yaron2** [comment]
@1046102779 can you explain what's the optimization here?

**Comment by yaron2** [comment]
@1046102779 thanks for this contribution. can you explain how this change reduces the "server logic processing" and specifically which logic you're  referring to here?

**Comment by tanvigour** [comment]
> @1046102779 thanks for this contribution. can you explain how this change reduces the "server logic processing" and specifically which logic you're referring to here?

+1 to Yaron's comment here. Please explain how this code addresses optimization. Thank you for your contribution!

**Comment by yaron2** [comment]
Closing due to author not responsive.

**Pull request closed without merging**
