### PR TITLE
Update config subscribe method

### PR DESCRIPTION
**Pull request by shivamkm07**
Closes Issue: #388

### CODE REVIEW

**Comment by shivamkm07** [comment]
Since this PR is a breaking change in subscribe method in go-sdk, should we just remove alpha1 endpoint for config API completely from go-sdk? @yaron2 @daixiang0 @mukundansundar

**Comment by mukundansundar** [comment]
> Since this PR is a breaking change in subscribe method in go-sdk, should we just remove alpha1 endpoint for config API completely from go-sdk? @yaron2 @daixiang0 @mukundansundar 

I agree that it should be removed in go sdk. @dapr/maintainers-go-sdk ?

**Comment by yaron2** [comment]
> > Since this PR is a breaking change in subscribe method in go-sdk, should we just remove alpha1 endpoint for config API completely from go-sdk? @yaron2 @daixiang0 @mukundansundar
> 
> I agree that it should be removed in go sdk. @dapr/maintainers-go-sdk ?

Yes for removal

**Comment by shivamkm07** [comment]
There is already an open PR for updating protos and removing alpha1 API: #391 . So I have removed these from the current PR. cc @yaron2 @daixiang0 @mukundansundar

**Comment by DeepanshuA** [comment]
> There is already an open PR for updating protos and removing alpha1 API: #391 . So I have removed these from the current PR. cc @yaron2 @daixiang0 @mukundansundar

@yaron2 @daixiang0 Please look into this PR. Once this PR is merged, change may be required in contrib as well for certification tests.

**Review by yaron2 — APPROVED** [review]

**Comment by mukundansundar** [comment]
@dapr/maintainers-go-sdk add to milestone 1.8

**Pull request merged**
