### PR TITLE
replace

### PR DESCRIPTION
**Pull request by riza-wartek**

### CODE REVIEW

**Comment by yaron2** [comment]
I'm closing this PR as it doesn't add anything of value.

Can you explain these changes?

**Comment by riza-wartek** [comment]
shoot, so sorry, I didn't know that this PR was created

**Comment by riza-wartek** [comment]
> I'm closing this PR as it doesn't add anything of value.
> 
> Can you explain these changes?

its related to this issue: https://github.com/dapr/go-sdk/issues/237

**Comment by yaron2** [comment]
Look at the files you committed, it's just a package rename.

**Comment by riza-wartek** [comment]
yes, this PR is a mistake

**Pull request closed without merging**
